modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="sao_mod"
version="1.0.0"
displayName="SAO Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="OmarRahmanK, ninichyu, MCreator"
description='''
A mod that adds SAO items and skills to minecraft.
'''

[[dependencies.sao_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




